### ISSUE TITLE
--server-name is not working on nsm_server_user-add

### ISSUE THREAD

**Issue by haginara** [Security-Onion-Solutions/securityonion-nsmnow-admin-scripts#15]
When I use the nsm_server_user-add script, the --server-name is not working.
I found the script assign the "securityonion" as the default SERVER_NAME after it assigned the SERVER_NAME by the arguments.

**Comment by dougburks** [comment]
Hi @haginara ,

The NSM scripts were originally written with the --server-name option to allow for future support of running multiple Sguil servers on one box.  That support never materialized, so all of our NSM scripts are currently hardcoded to a single server-name of "securityonion".  Since that is the default, you shouldn't ever need to pass the --server-name option.
